version: '2'
services:
  nanopubgate:
    build: .
    environment:
      - NPG_TYPES="http://example.com/typeA http://example.com/typeB"
      - NPG_POST_NANOPUBS_TO=http://example.com/sparql-endpoint-url
    ports:
      - 8080:8080